### PR TITLE
fix invites and multiple issues with permissions

### LINKED ISSUE #149: Add message after submitting a new invitation
When you invite a new user there is no feedback message that the invite was sent.

### PR DESCRIPTION
**Pull request by Panioglo**
Fixes #149, #150, #151

### CODE REVIEW

File: app/controllers/invites_controller.rb [hunk 1]
```diff
@@ -15,13 +15,13 @@ def accept
     if !logged_in?
       # we redirect to signup url because we are not logged in
       redirect_to signup_url( token: params[:id] )
-    elsif @invite.email.casecmp(current_user.email) == 0
+    elsif current_user && @invite.email.casecmp(current_user.email) == 0
```
Comment (Chocksy) [inline app/controllers/invites_controller.rb]: Please remove this check. Why is this necessary? We already have an if above that verifies if you are logged in.

File: app/controllers/invites_controller.rb [hunk 2]
```diff
@@ -15,13 +15,13 @@ def accept
...
       @invite.accept(current_user)
       set_website(@invite.website)
       # it will redirect to errors url because we set the website for the user
       after_login_redirect
-    else
-      # it will redirect to create website wizard because we don't sent it
+    elsif current_user && @invite.email.casecmp(current_user.email) == 1
```
Comment (Chocksy) [inline app/controllers/invites_controller.rb]: Same here this has no use of being here.

File: app/controllers/users_controller.rb [hunk 3]
```diff
@@ -32,18 +32,14 @@ def create
 
   def confirm
     user = User.find_by_id_and_confirmation_token(params[:id], params[:token])
+    logout if logged_in? && user
     if user.nil?
       redirect_to login_url, alert: 'Bad url'
     elsif !user.confirmed_at.blank?
```
Comment (Chocksy) [inline app/controllers/users_controller.rb]: Here use `elsif user.confirmed?`

File: app/controllers/invites_controller.rb (hunk 1 above)
Comment (Panioglo) [inline app/controllers/invites_controller.rb]: yep, my bad

File: app/controllers/website_wizard_controller.rb [hunk 4]
```diff
@@ -25,6 +25,8 @@ def update
         redirect_to next_wizard_path
         # render_wizard
       else
+        #notice with an active model error
+        flash[:notice] =  @website.errors.messages[:website].try(:first)
```
Comment (Chocksy) [inline app/controllers/website_wizard_controller.rb]: Why are you picking what errors to show? Use the `full_messages` method

File: app/models/ability.rb [hunk 5]
```diff
@@ -4,27 +4,24 @@ class Ability
...
+      can :read, Website do |website|
+        user.is_user_of?(website)
+      end
       can :create, Website
       can :manage, WebsiteMember do |website_member|
         user.is_owner_of?(website_member.website)
       end
       can :read, WebsiteMember do |website_member|
-        website_member.website.members.include?(user)
+        website_member.website.is_user_of?(user)
```
Comment (Chocksy) [inline app/models/ability.rb]: This is wrong. `is_user_of?` is a method that belongs to the user model not the website model.

File: app/controllers/users_controller.rb (hunk 3 above)
Comment (Panioglo) [inline app/controllers/users_controller.rb]: ok, this code was older than confirmed? method, my bad I didn't pay attention to that line

File: app/controllers/website_wizard_controller.rb (hunk 4 above)
Comment (Panioglo) [inline app/controllers/website_wizard_controller.rb]: I tried to get rid of that errors.add :base  and flash a message in the controller, but then our method  was always returning true and return false didn't help. I'll use the full messages method

Comment (Panioglo) [inline app/controllers/website_wizard_controller.rb]: This error is raised when checking for duplicate websites in our website.rb file.. forgot to tell in the above

File: app/controllers/application_controller.rb [hunk 6]
```diff
@@ -56,8 +55,11 @@ def after_login_redirect(url_to_redirect = nil)
     redirect_to(url_to_redirect) && return unless url_to_redirect.nil?
     if current_website
       redirect_to errors_url, notice: "Logged in"
+    elsif !current_user.websites.empty?
+      set_website(current_user.websites.first)
+      redirect_to errors_url
```
Comment (Chocksy) [inline app/controllers/application_controller.rb:57]: I don't understand why you need this. This should be done in a controller where this is called. You don't set a website here at random. Can you explain?

File: app/controllers/errors_controller.rb [hunk 7]
```diff
@@ -44,7 +44,7 @@ def update
   def notify_subscribers
     unless params[:message].blank?
       @message = Message.create( content: params[:message], issue_id: @error.issues.last.id )
-      @error.website.users.each do |user|
+      @error.website.subscribers.each do |user|
         GroupedIssueMailer.notify_subscriber(@error, user, current_user, @message).deliver_later
```
Comment (Chocksy) [inline app/controllers/errors_controller.rb]: I think we need to change the each argument too from `user -> subscriber` just so we can be correct and not give false impressions.

File: app/controllers/invites_controller.rb [hunk 8]
```diff
@@ -20,8 +20,8 @@ def accept
       set_website(@invite.website)
       # it will redirect to errors url because we set the website for the user
       after_login_redirect
-    else
-      # it will redirect to create website wizard because we don't sent it
+    elsif @invite.email.casecmp(current_user.email) == 1
+      # it will redirect to website wizard url because emails don't match
       after_login_redirect
```
Comment (Chocksy) [inline app/controllers/invites_controller.rb:21]: Why did you add this? We don't care if the email is different. We should redirect to `after_login_redirect` in call cases. In fact there is probably other way than that. So why the explicit check?

File: app/controllers/subscribers_controller.rb [hunk 9]
```diff
@@ -1,5 +1,11 @@
 class SubscribersController < ApplicationController
+	load_and_authorize_resource
```
Comment (Chocksy) [inline app/controllers/subscribers_controller.rb]: There is a weird indentation here.

File: app/controllers/subscribers_controller.rb [hunk 10]
```diff
@@ -1,5 +1,11 @@
...
   def index
     @subscribers = current_website.subscribers
   end
+
+  def destroy
+    @subscriber.destroy
+    redirect_to subscribers_url
```
Comment (Chocksy) [inline app/controllers/subscribers_controller.rb:9]: there are no specs for this method.

File: app/controllers/website_wizard_controller.rb [hunk 11]
```diff
@@ -25,6 +25,8 @@ def update
         redirect_to next_wizard_path
         # render_wizard
       else
+        #notice with an active model error
+        flash[:notice] =  @website.errors.full_messages.try(:first)
```
Comment (Chocksy) [inline app/controllers/website_wizard_controller.rb]: Why are you picking only the first message here?

File: app/controllers/websites_controller.rb [hunk 12]
```diff
@@ -7,25 +7,23 @@ def index
...
-      unless current_user.websites.blank?
-        set_website(current_user.websites.first)
-        format.js { render inline: 'location.reload();' }
-      end
-      format.js { render inline: "location.href='#{website_wizard_path(:create)}';" } if current_user.websites.blank?
+    unless current_user.websites.blank?
+      set_website(current_user.websites.first)
+      redirect_to websites_url
     end
+    website_wizard_url(:create) if current_user.websites.blank?
```
Comment (Chocksy) [inline app/controllers/websites_controller.rb]: Do a simple `if .. else .. end` block here instead of doing unless and then another if.

File: app/models/ability.rb [hunk 13]
```diff
@@ -4,27 +4,24 @@ class Ability
...
-      end
-      can :manage, Issue do |issue|
-        user.is_owner_of?(issue.group.website)
-      end
-      can :manage, Message do |message|
-        user.is_owner_of?(message.issue.group.website)
-      end
+      can :manage, GroupedIssue
+      can :manage, Issue
+      can :manage, Message
```
Comment (Chocksy) [inline app/models/ability.rb]: In this case here you gave access to any user to access any grouped_issue, issue or message. It doesn't matter if the user is a part of the website that these records belong to. You should add some specs for permissions and for these check if the user is a member of the website these records belong to.

File: app/controllers/invites_controller.rb (hunk 8 above)
Comment (Panioglo) [inline app/controllers/invites_controller.rb:21]: then why do we still need email column in the invites table?

File: app/controllers/website_wizard_controller.rb (hunk 11 above)
Comment (Panioglo) [inline app/controllers/website_wizard_controller.rb]: I need this to rid of [ ' ' ]

File: app/views/layouts/_error_sidebar.html.haml [hunk 14]
```diff
@@ -13,5 +13,14 @@
...
+          %button.btn.btn-link.dropdown-toggle.btn-block{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", "data-target" => "#icon-dropdown", :type => "button"}
+            = image_tag current_user.avatar_url, class: 'avatar'
+%ul.dropdown-menu#icon-dropdown
+  %li
+    %a{:href => "#{websites_url()}"} Websites
+  %li
+    = link_to "Account", edit_user_path(current_user)
+  %li.divider{:role => "separator"}
+  %li
+    = link_to 'Logout', logout_url, method: :delete
```
Comment (Chocksy) [inline app/views/layouts/_error_sidebar.html.haml:26]: Is this a problem of indentation because it's not very clear that this is the correct code..

File: app/controllers/application_controller.rb (hunk 6 above)
Comment (hyperionel) [inline app/controllers/application_controller.rb:57]: There's a situation where the 'add website wizard' pops up after logging in even if you already have a website added. It happens when the website is not set in the session. For example when logging in with github.

File: app/controllers/invites_controller.rb (hunk 8 above)
Comment (Chocksy) [inline app/controllers/invites_controller.rb:21]: The idea is that you are making a check to see if the emails are different when it's clear they are because we are making a check in the above elsif to see if they are the same. So as a logical consequence it's clear that this else will only happen if the email is different and you are not logged in. !!

Comment (Chocksy) [inline app/controllers/invites_controller.rb:21]: In short there is no need for this check to see if the email is different as it already happens.

File: app/controllers/website_wizard_controller.rb (hunk 11 above)
Comment (Chocksy) [inline app/controllers/website_wizard_controller.rb]: Use a `join(', ')` to join all the errors.

File: app/views/layouts/_error_sidebar.html.haml (hunk 14 above)
Comment (hyperionel) [inline app/views/layouts/_error_sidebar.html.haml:26]: No it isn't. I couldn't find a way to display it inside the #sidebar-wrapper since its wider

File: app/controllers/application_controller.rb (hunk 6 above)
Comment (Chocksy) [inline app/controllers/application_controller.rb:57]: Well in that situation we should set the website in the auth_controller when you go in from the github button not here. I can see how this could be convenient but i don't wanna get into weird issues because of this. We will be calling this method everywhere so it should just redirect and nothing else.

File: app/views/layouts/_error_sidebar.html.haml (hunk 14 above)
Comment (Chocksy) [inline app/views/layouts/_error_sidebar.html.haml:26]: Ok if it works as expected then we can leave it like this!.

File: app/views/layouts/_error_sidebar.html.haml [hunk 15]
```diff
@@ -13,5 +13,14 @@
...
       %li
-        %a{:href => ""}
-          = image_tag current_user.avatar_url, class: 'avatar'
\ No newline at end of file
+        .dropdown
+          %button.btn.btn-link.dropdown-toggle.btn-block{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", "data-target" => "#icon-dropdown", :type => "button"}
+            = image_tag current_user.avatar_url, class: 'avatar'
+%ul.dropdown-menu#icon-dropdown
+  %li
+    %a{:href => "#{websites_url()}"} Websites
```
Comment (Chocksy) [inline app/views/layouts/_error_sidebar.html.haml]: Why are we doing link_to for the links below but here we are using an anchor tag. Use the link_to for websites too.

File: app/controllers/website_members_controller.rb [hunk 16]
```diff
@@ -6,7 +6,10 @@ def index
 
   def destroy
     @website_member.destroy
-    return false unless @website_member.errors.full_messages.blank?
-    redirect_to website_members_path, notice: 'Member removed'
+    if @website_member.errors.full_messages.blank?
+	    redirect_to website_members_url
+	  else
+	    redirect_to website_members_url, notice: @website_member.errors.full_messages.join(', ')
+	  end
```
Comment (Chocksy) [inline app/controllers/website_members_controller.rb]: indentation is weird here.

File: app/models/ability.rb [hunk 17]
```diff
@@ -4,27 +4,28 @@ class Ability
...
-      end
+      can :manage, GroupedIssue
       can :manage, Issue do |issue|
-        user.is_owner_of?(issue.group.website)
+        user.is_owner_of?(issue.website)
       end
       can :manage, Message do |message|
-        user.is_owner_of?(message.issue.group.website)
+        user.is_owner_of?(message.subscriber.website)
       end
```
Comment (Chocksy) [inline app/models/ability.rb:15]: we need to allow users to do these:
- `:manage, Message`
- `[:read, :update], Issue`
- `[:read, :update], GroupedIssue`

We need to allow owners to:
- `:manage, Message`
- `:manage, GroupedIssue`
- `:manage, Issue`

We are talking about users and owners of the website that these records belong to.

File: spec/controllers/installations_controller_spec.rb [hunk 18]
```diff
@@ -1,5 +1,36 @@
...
 
+  describe '#index' do
+  	it 'should assign website' do
+  		get_with user, :index
+      expect(assigns(:website)).to eq(website)
+  	end
+
+  	it 'should assign default tabs' do
+  		get_with user, :index
+      expect(assigns(:main_tab)).to eq('details')
```
Comment (Chocksy) [inline spec/controllers/installations_controller_spec.rb:17]: weird indentation.

File: spec/controllers/subscribers_controller_spec.rb [hunk 19]
```diff
@@ -1,8 +1,35 @@
...
+  describe "GET #index" do
+    it 'should get subscribers' do
+    	get_with user, :index
+    	expect(assigns(:subscribers)).to eq([subscriber])
+    end
+  end
+
+  describe "DELETE #destroy" do
+    it 'should delete record' do
+    	subscriber2 = create :subscriber, website: website
```
Comment (Chocksy) [inline spec/controllers/subscribers_controller_spec.rb]: weird indentation

File: app/models/ability.rb (hunk 17 above)
Comment (Panioglo) [inline app/models/ability.rb:15]: if we change :manage, GroupedIssue line then the invited user is not able to access /error#show
I've tried `[:read, :update], GroupedIssue` too

File: spec/models/ability_spec.rb [hunk 20]
```diff
@@ -0,0 +1,55 @@
...
+        subject(:ability){ Ability.new(owner) }
+
+        it { is_expected.to be_able_to(:manage, owner) }
+        it { is_expected.not_to be_able_to(:manage, user) }
+        it { is_expected.to be_able_to(:manage, website) }
+        it { is_expected.to be_able_to(:manage, user_website_member_with_user) }
+        it { is_expected.to be_able_to(:manage, owner_website_member_with_user) }
+        it { is_expected.to be_able_to(:manage, issue) }
+        it { is_expected.to be_able_to(:manage, subscriber) }
+        it { is_expected.to be_able_to(:manage, message) }
```
Comment (Chocksy) [inline spec/models/ability_spec.rb]: we need to test for other website users. So create a new website and assign users to it and then test that those users don't have the ability to manage grouped issues and stuff.
