### PR TITLE
fixed bug with nil http_data

### LINKED ISSUE #182: Fix bug with nil http_data
We get this error when the http_data info is nil.
image

### PR DESCRIPTION
**Pull request by Panioglo**
Fixes #182, #168

### CODE REVIEW

File: app/models/issue.rb [hunk 1]
```diff
@@ -20,7 +20,7 @@ def get_interfaces(interface = nil)
 
   def get_headers(header = nil)
     all_headers = http_data(:headers)
-    return all_headers if header.nil?
+    return all_headers if header.nil? || all_headers == "<no information>"
     all_headers.find { |h| h[header] }.try(:values).try(:first)
```
Comment (Chocksy) [inline app/models/issue.rb:24]: ahhhh... this is why i have returning strings for no values. I know we agreed we should keep this but really we should change it. Please stop returning strings for these. `all_headers` should be nil in this case. If we want to show some kind of string and use that method in mailers we should make a new one that checks if the returned data is nil.
