### PR TITLE
fixed the email when there is no stacktrace

### LINKED ISSUE #200: Fix the mail when there is no stacktrace
We need to show the other information like http and other interfaces data if there is no stacktrace in the email. http://take.ms/r4Crc this email is not helpful at all. Also we need to link to the error on our website.

### PR DESCRIPTION
**Pull request by Panioglo**
Fixes #200, #202

### CODE REVIEW

File: app/controllers/website_members_controller.rb [hunk 1]
```diff
@@ -10,8 +11,11 @@ def update
   end
 
   def change_role
-    @website_member.update_attributes(website_member_role_params) if website_member_role_params[:role].present?
-    redirect_to settings_url, notice: 'Role updated'
+    current_website_member = WebsiteMember.find_by_user_id_and_website_id(current_user.id, current_website.id)
+    if current_website_member.role.owner?
+      @website_member.update_attributes(website_member_role_params)
+      render json: @website_member
+    end
```
Comment (Chocksy) [inline app/controllers/website_members_controller.rb:19]: I want you to confirm that if a user tries to change the role we are rendering a json and telling them that they don't have permission. Is that correct?

File: app/views/website_members/index.html.haml [hunk 2]
```diff
@@ -18,9 +19,13 @@
...
\ No newline at end of file
+            - unless @current_website_member == website_member
+              = simple_form_for website_member, wrapper: :vertical_form do |f|
+                %tr
+                  %input{:name => "id", :type => "hidden", :value => "#{website_member.id}"}/
+                  %td= website_member.user.name
+                  %td= website_member.user.email
+                  %td
+                    = f.input :role, label: false, collection: [['Owner', 1], ['User', 2]], selected: website_member.role.value, input_html: {:style => "max-width: 90px;"}
+                  %td.text-right
```
Comment (Chocksy) [inline app/views/website_members/index.html.haml]: Why do you have a form if you are not submitting anything. This is also wrong as it's in a table. There is no reason for that form there you are doing an ajax call...

File: app/views/website_members/index.html.haml [hunk 3]
```diff
@@ -18,9 +19,13 @@
...
-                = link_to ' Delete', "/website_members/#{website_member.id}", :method => :delete, data: {confirm: "Are you sure?"}, :class => "delete_website btn btn-danger pull-right fa fa-close"
\ No newline at end of file
+            - unless @current_website_member == website_member
+              = simple_form_for website_member, wrapper: :vertical_form do |f|
+                %tr
+                  %input{:name => "id", :type => "hidden", :value => "#{website_member.id}"}/
+                  %td= website_member.user.name
+                  %td= website_member.user.email
+                  %td
+                    = f.input :role, label: false, collection: [['Owner', 1], ['User', 2]], selected: website_member.role.value, input_html: {:style => "max-width: 90px;"}
```
Comment (Chocksy) [inline app/views/website_members/index.html.haml]: for this i think you should do something like this line of code:

```
= select_tag 'role', options_for_select(options, selected: membership.role), id: nil, class: 'ajax-spinner', style: 'width: 100%;', data: { remote: true, url: change_role_website_member_path(website_member), method: 'put', params: '_method=put', type: 'json' }
```

It takes the need for any ajax/js code that you wrote and it works out of the box

File: app/views/website_members/index.html.haml [hunk 4]
```diff
@@ -18,9 +19,13 @@
...
+            - unless @current_website_member == website_member
+              = simple_form_for website_member, wrapper: :vertical_form do |f|
+                %tr
+                  %input{:name => "id", :type => "hidden", :value => "#{website_member.id}"}/
+                  %td= website_member.user.name
+                  %td= website_member.user.email
+                  %td
+                    = select_tag 'website_member_role[role]', options_for_select([['Owner', 1], ['User', 2]], selected: website_member.role.value), id: nil, style: 'max-width: 90px;', data: { remote: true, url: change_role_website_member_path(website_member), method: 'put', params: '_method=put', type: 'json' }
+                  %td.text-right
+                    = link_to ' Delete', "/website_members/#{website_member.id}", :method => :delete, data: {confirm: "Are you sure?"}, :class => "delete_website btn btn-danger pull-right fa fa-close"
```
Comment (Chocksy) [inline app/views/website_members/index.html.haml]: use for url here `website_member_url(website_member)` instead of building it by hand

File: app/views/website_members/index.html.haml [hunk 5]
```diff
@@ -18,9 +19,12 @@
...
         %tbody.websites
           - @website_members.each do |website_member|
-            %tr
-              %td= website_member.user.name
-              %td= website_member.user.email
-              %td= website_member.role
-              %td.text-right
-                = link_to ' Delete', "/website_members/#{website_member.id}", :method => :delete, data: {confirm: "Are you sure?"}, :class => "delete_website btn btn-danger pull-right fa fa-close"
\ No newline at end of file
+            - unless @current_website_member == website_member
```
Comment (Chocksy) [inline app/views/website_members/index.html.haml]: let's not do this stupid thing here and just not select the current user by adjusting the query in the controller
