### PR TITLE
fix admin after removal of devise

### LINKED ISSUE #139: Fix admin after removal of devise
- [ ] verify that the authentication works using the user model
- [ ] add roles to user model and use that to verify if an user has access to the admin
- [ ] make sure that the admin controllers work after the update

### PR DESCRIPTION
**Pull request by Panioglo**
Fixes #139

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -16,6 +16,19 @@ class ApplicationController < ActionController::Base
 
   protected
 
+  def current_admin_user
+    return current_user if current_user && current_user.role == "admin"
```
Comment (Chocksy) [inline app/controllers/application_controller.rb]: you can use `current_user.admin?` here if you add to the enumerize declaration `predicates: true`. Also we need to return nil not false as this is not a question method.

File: app/controllers/application_controller.rb [hunk 2]
```diff
@@ -16,6 +16,19 @@ class ApplicationController < ActionController::Base
...
+    return false
+  end
+
+  def authenticate_admin_user!
+    if current_admin_user
+      flash[:notice] = "Hi #{current_user.name}"
+    else
+      redirect_to errors_path, notice: 'Admin role required'
```
Comment (Chocksy) [inline app/controllers/application_controller.rb]: There is also the case where the user might not be logged in. You can't redirect him to the errors_path in that case. I know it will actually get him to login if that doesn't work but this is not good logic.

File: app/controllers/users_controller.rb [hunk 3]
```diff
@@ -43,6 +43,12 @@ def confirm
     end
   end
 
+  def unconfirm
```
Comment (Chocksy) [inline app/controllers/users_controller.rb]: This name is so weird. `unconfirm` is like i would like to remove the confirmation for this user but you are `reconfirming` actually. It should probably be `resend_confirmation`.

File: app/models/user.rb [hunk 4]
```diff
@@ -45,7 +47,12 @@ def confirmed?
     !confirmed_at.blank?
   end
 
-  def send_confirmation
+  def confirm
+    update_attributes(confirmation_token: nil, confirmed_at: Time.now.utc)
+  end
+
+  def send_confirmation(unconfirm = false)
+    self.confirmed_at = nil if unconfirm
```
Comment (Chocksy) [inline app/models/user.rb]: why are we removing the confirmation from a user?

File: config/routes.rb [hunk 5]
```diff
@@ -33,6 +32,7 @@
   resources :users, only: [:index, :edit, :update] do
     member do
       get :confirm
+      get :unconfirm
```
Comment (Chocksy) [inline config/routes.rb]: we don't need this.

File: app/models/user.rb (hunk 4 above)
Comment (Panioglo) [inline app/models/user.rb]: I updated this method to avoid duplicated code.. we need this method, and the one above for active admin.

Comment (Chocksy) [inline app/models/user.rb]: Nah let's not remove the confirmation from people. Remove that option.

File: app/admin/user.rb [hunk 6]
```diff
@@ -66,12 +69,8 @@
...
   end
 
-  action_item :show, if: proc { !member.confirmed? } do
-    link_to 'Confirm member', confirm_admin_member_path(member), method: :put
-  end
-
-  action_item :show, if: proc { member.confirmed? } do
-    link_to 'Unconfirm member', unconfirm_admin_member_path(member), method: :put
+  action_item :show, if: proc { !user.confirmed? } do
+    link_to 'Confirm user', confirm_user_url(id: user.id, token: user.confirmation_token), method: :get
```
Comment (Chocksy) [inline app/admin/user.rb:73]: Don't send them to this url. They should be redirected to the admin confirm action.

File: app/controllers/application_controller.rb [hunk 7]
```diff
@@ -16,6 +16,19 @@ class ApplicationController < ActionController::Base
 
   protected
 
+  def current_admin_user
+    return current_user if current_user.admin?
+    return nil
```
Comment (Chocksy) [inline app/controllers/application_controller.rb:21]: there is no need for a return nil here as it will return nil if the condition is not met.

File: app/controllers/users_controller.rb [hunk 8]
```diff
@@ -32,14 +32,18 @@ def create
...
       redirect_to login_url, alert: 'You confirmed your email once'
     else
       user.update_attributes(confirmation_token: nil, confirmed_at: Time.now.utc)
-      redirect_to login_url, notice: "Account confirmed"
+      unless current_user.admin?
+        logout if logged_in? && user
+        redirect_to login_url, notice: "Account confirmed"
+      else
+        redirect_to admin_user_url(user), notice: "You have just confirmed #{user.name}'s account}"
+      end
```
Comment (Chocksy) [inline app/controllers/users_controller.rb:46]: remove this please.

Comment (Panioglo) [inline app/controllers/users_controller.rb:46]: There is a missing template error, and I use a redirect to avoid this.
